gem code
artem247/code-breaker-gem pull request #1
Opened 2020-07-15 10:08 UTC by artem247

Codebreaker gem code,
lintered, but no rspec at this moment

2020-07-15 11:09 UTC, katiakub requested changes

2020-07-15 11:09 UTC, katiakub commented on Gemfile
> +gem "rake", "~> 12.0"
move it to gemspec, pls

2020-07-15 11:09 UTC, katiakub commented on lib/codebreaker/helpers/validators.rb
> +      case type
nice idea)

2020-07-15 13:19 UTC, Dimasfullxq requested changes

2020-07-15 13:19 UTC, Dimasfullxq commented on lib/codebreaker/models/game.rb
> +        code << (1..6).to_a.sample
I think it would be cool if  move range (1..6) to constant

2020-07-15 13:38 UTC, Dimasfullxq requested changes

2020-07-15 13:38 UTC, Dimasfullxq commented on lib/codebreaker/models/game.rb
> +      hint_index = rand(0...4)
What if code size change, you need to change your 4. Imho It would be cool to use CODE.size here.

2020-07-15 19:32 UTC, Dimasfullxq commented on lib/codebreaker/helpers/validators.rb
> +      case type
tricky way, why not

2020-07-17 12:14 UTC, artem247 commented on Gemfile
> +gem "rake", "~> 12.0"
fixed

2020-07-17 12:14 UTC, artem247 commented on lib/codebreaker/models/game.rb
> +        code << (1..6).to_a.sample
fixed, thank you

2020-07-17 12:15 UTC, artem247 commented on lib/codebreaker/models/game.rb
> +      hint_index = rand(0...4)
yes, added that, thank you

2020-07-17 13:14 UTC, Dimasfullxq requested changes

2020-07-17 13:14 UTC, Dimasfullxq commented on lib/codebreaker/models/game.rb
> +      code = []
Use map instead of [ ]. You can do something like that 

```(1..CODE_SIZE).map { code_range.to_a.sample } ```
and if you want code to be an integer add ``` .join.to_i ```

2020-07-17 13:20 UTC, Dimasfullxq requested changes

2020-07-17 13:20 UTC, Dimasfullxq commented on lib/codebreaker/models/game.rb
> +      hint_index = rand(0...CODE_SIZE)
Imho it can't work correctly, when you take a hint you delete one element from @hint_list. When user wants to take a hint again, method will be searching by indexes 0..3, but hints already don't have such indexes cause you are using CODE_SIZE that is always 4.

2020-07-17 13:43 UTC, katiakub requested changes
wait for specs)

2020-07-17 13:43 UTC, katiakub commented on spec/codebreaker_spec.rb
> +  it "does something useful" do
delete it, because it's the only example of failed spec ;)

2020-07-17 13:43 UTC, katiakub commented on lib/codebreaker/models/game.rb
> +    def create_stats
maybe write value like { name: @player.name, difficulty: @ difficulty... }
I think this is more clearly

2020-07-17 13:43 UTC, katiakub commented on codebreaker.gemspec
> +  spec.required_ruby_version = Gem::Requirement.new(">= 2.3.0")
are you sure that this is the right required ruby version?)

2020-07-17 13:43 UTC, katiakub commented on lib/codebreaker/models/game.rb
> +      secret_code = code.dup
why not just @secret_code.dup?

2020-07-17 13:43 UTC, katiakub commented on lib/codebreaker/models/game.rb
> +      DEFAULT_DIFFICULTIES.dig(difficulty, :attempts)
why not just @difficulty?
why do you pass this parameter?)

2020-07-18 10:37 UTC, artem247 commented on lib/codebreaker/models/game.rb
> +      hint_index = rand(0...CODE_SIZE)
fixed

2020-07-20 14:04 UTC, artem247 commented on lib/codebreaker/models/game.rb
> +      code = []
got it

2020-07-20 14:04 UTC, artem247 commented on spec/codebreaker_spec.rb
> +  it "does something useful" do
Thanks :)

2020-07-20 14:04 UTC, artem247 commented on lib/codebreaker/models/game.rb
> +    def create_stats
got it, yes

2020-07-20 14:05 UTC, artem247 commented on codebreaker.gemspec
> +  spec.required_ruby_version = Gem::Requirement.new(">= 2.3.0")
of course, thanks for the tip

2020-07-20 14:05 UTC, artem247 commented on lib/codebreaker/models/game.rb
> +      secret_code = code.dup
changed it in current implementation

2020-07-22 23:51 UTC, Dimasfullxq requested changes

2020-07-22 23:51 UTC, Dimasfullxq commented on codebreaker.gemspec
> +  spec.add_development_dependency 'rubocop-performance', '~> 1.6.1'
Have you used rubocop rspec? If you haven't I'd like you to use it.

2020-07-22 23:51 UTC, Dimasfullxq commented on lib/codebreaker/services/generate_code.rb
> +  class GenerateCode
Nit: Imho, I think you should name your class like substantive not like verb.

2020-07-22 23:51 UTC, Dimasfullxq commented on spec/difficulty_spec.rb
> +  RSpec.describe Difficulty do
If your entity has only private methods, you could test only initialize or maybe entity fields.

2020-07-22 23:51 UTC, Dimasfullxq commented on spec/game_spec.rb
> +    describe 'initialization' do
It would be cool if you start your main blocks with method name like ".initialize" if it's class method and  "#hint" if it's instance one.

2020-07-23 14:33 UTC, DaniilYusha requested changes

2020-07-23 14:33 UTC, DaniilYusha commented on lib/codebreaker.rb
> +
nit: I think it would be better to group your requires like:
`require 'yaml'

require_relative 'codebreaker/helpers/defaults'
require_relative 'codebreaker/helpers/validators'

require_relative 'codebreaker/services/code_generator'
require_relative 'codebreaker/services/guess_parser'

require_relative 'codebreaker/errors/class_error'
require_relative 'codebreaker/errors/guess_error'`
It makes this file more readable

2020-07-23 14:33 UTC, DaniilYusha commented on lib/codebreaker/services/guess_parser.rb
> +      guess.zip(secret_code).map { |a, b| a if a == b }
nit: please, rename your `a` and `b` to more understandable names. Try `secret_code_digit` and `guess_digit` or something else

2020-07-23 14:43 UTC, artem247 commented on codebreaker.gemspec
> +  spec.add_development_dependency 'rubocop-performance', '~> 1.6.1'
Thank you, missed that - added now

2020-07-23 14:43 UTC, artem247 commented on lib/codebreaker/services/generate_code.rb
> +  class GenerateCode
I agree

2020-07-23 14:44 UTC, artem247 commented on spec/difficulty_spec.rb
> +  RSpec.describe Difficulty do
Added tests there

2020-07-23 14:44 UTC, artem247 commented on spec/game_spec.rb
> +    describe 'initialization' do
Got you, yes, I've fixed that

2020-07-23 14:46 UTC, artem247 commented on lib/codebreaker.rb
> +
Good idea - added that.

2020-07-23 14:52 UTC, artem247 commented on lib/codebreaker/services/guess_parser.rb
> +      guess.zip(secret_code).map { |a, b| a if a == b }
yes, added that, thanks

2020-07-24 09:13 UTC, DaniilYusha approved these changes

2020-07-25 20:16 UTC, exposwingie approved these changes
Looks good

2020-07-25 20:18 UTC, Dimasfullxq approved these changes

2020-07-25 20:19 UTC, exposwingie approved these changes

2020-07-27 15:38 UTC, Svatok commented on lib/codebreaker/helpers/validators.rb
> +      true
Any other command will by valid?

2020-07-27 17:03 UTC, artem247 commented on lib/codebreaker/helpers/validators.rb
> +      true
I see, yes, in current implementation any other command will be by default valid,
I will update it today

2020-07-27 17:26 UTC, artem247 commented on lib/codebreaker/helpers/validators.rb
> +      true
@Svatok updated, now it will raise a special error for any other command

2020-07-29 15:06 UTC, Svatok approved these changes

2020-07-29 15:06 UTC, Svatok commented on lib/codebreaker/helpers/validators.rb
> +      true
Do we need `true` here?

2023-09-24 10:47 UTC, merged